### ISSUE TITLE
not showing any possible results

### ISSUE THREAD

**Issue by yashsinghcodes** [MichaelDim02/houndsniff#6]
I have installed houndsniff but it does not show me any possible results i have tried SHA256 and MD5 but no results.
I am using:
OS: Arch Linux x86_64
Kernel: 5.15.12
WM: DWM
Terminal: st
Shell: zsh

Attaching some screenshot
![pic-selected-220205-1926-39](https://user-images.githubusercontent.com/32360914/152645093-188d7249-fa38-46b7-ad53-53f67411406a.png)

**Comment by MichaelDim02** [comment]
Hello.

SHA256 and MD5 hashes are in numbers in hexadecimal, and should be 0-9, a-f. They're not supposed to include upper case letters (A-F). Houndsniff is programmed to consider those two separate charactersets.

What program did you use to generate those hashes?

**Comment by yashsinghcodes** [comment]
Oh yes, i got it i used some only hash generator and did not notice that they were all in upper case its totally my fault.
